export const INIT_SUBJECT_LIST = 'INIT_SUBJECT_LIST';
export const ADD_SUBJECT_LIST = 'ADD_SUBJECT_LIST';
export const REMOVE_SUBJECT_LIST = 'REMOVE_SUBJECT_LIST';
export const UPDATE_SUBJECT_LIST = 'UPDATE_SUBJECT_LIST';
